<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Permission extends \Spatie\Permission\Models\Permission
{
    public function roles(): BelongsToMany
    {
        return parent::roles(); // TODO: Change the autogenerated stub
    }
}
