<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Role extends \Spatie\Permission\Models\Role
{
    public function permissions(): BelongsToMany
    {
        return parent::permissions(); // TODO: Change the autogenerated stub
    }
}
